#!/bin/bash
# LocalBookr Complete Deployment Script
# Usage: ./deploy.sh [github-repo-url]

echo "🚀 LocalBookr Platform Deployment Started..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if required tools are installed
check_command() {
    if ! command -v $1 &> /dev/null; then
        echo -e "${RED}❌ $1 not found. Installing...${NC}"
        npm install -g $1
    fi
}

# Get GitHub repository URL from argument or prompt
if [ -z "$1" ]; then
    echo -e "${BLUE}📋 Enter your GitHub repository URL:${NC}"
    read -p "GitHub URL: " GITHUB_REPO
else
    GITHUB_REPO="$1"
fi

# Validate GitHub URL
if [[ ! "$GITHUB_REPO" =~ ^https://github.com/.* ]]; then
    echo -e "${RED}❌ Invalid GitHub URL format${NC}"
    echo "Expected: https://github.com/username/repository"
    exit 1
fi

echo -e "${BLUE}📊 Deployment Configuration:${NC}"
echo "Repository: $GITHUB_REPO"
echo "Timestamp: $(date +'%Y%m%d_%H%M%S')"

# Step 1: Git Repository Setup
echo -e "${YELLOW}🔄 Setting up Git repository...${NC}"

if [ ! -d ".git" ]; then
    git init
    git add .
    git commit -m "Initial commit: Complete LocalBookr platform"
    git branch -M main
fi

git remote add origin "$GITHUB_REPO" 2>/dev/null || true

echo -e "${GREEN}✅ Git repository ready${NC}"

# Step 2: Check for required tools
echo -e "${YELLOW}🔧 Checking deployment tools...${NC}"
check_command "netlify"
check_command "supabase"
echo -e "${GREEN}✅ Deployment tools ready${NC}"

# Step 3: Install all dependencies
echo -e "${YELLOW}📦 Installing all dependencies...${NC}"
npm run install:all
echo -e "${GREEN}✅ Dependencies installed${NC}"

# Step 4: Deploy Frontend to Netlify
echo -e "${YELLOW}🌐 Deploying frontend to Netlify...${NC}"

# Build all frontend applications
echo -e "${BLUE}Building customer app...${NC}"
cd frontend && npm run build
echo -e "${BLUE}Building admin dashboard...${NC}"
cd ../admin-dashboard && npm run build
echo -e "${BLUE}Building partner dashboard...${NC}"
cd ../partner-dashboard && npm run build
cd ..

# Deploy each app to Netlify
echo -e "${YELLOW}Deploying customer app...${NC}"
netlify deploy --prod --dir=frontend/.next --site=localbookr-customer --message="Customer app deployment $TIMESTAMP" || {
    echo -e "${RED}❌ Customer app deployment failed${NC}"
    FRONTEND_SUCCESS=false
}

echo -e "${YELLOW}Deploying admin dashboard...${NC}"
netlify deploy --prod --dir=admin-dashboard/.next --site=localbookr-admin --message="Admin dashboard deployment $TIMESTAMP" || {
    echo -e "${RED}❌ Admin dashboard deployment failed${NC}"
    FRONTEND_SUCCESS=false
}

echo -e "${YELLOW}Deploying partner dashboard...${NC}"
netlify deploy --prod --dir=partner-dashboard/.next --site=localbookr-partner --message="Partner dashboard deployment $TIMESTAMP" || {
    echo -e "${RED}❌ Partner dashboard deployment failed${NC}"
    FRONTEND_SUCCESS=false
}

# Step 5: Deploy Backend to Railway/Render
echo -e "${YELLOW}⚙ Deploying backend to Railway...${NC}"

if command -v railway &> /dev/null; then
    # Deploy to Railway
    echo -e "${BLUE}Deploying to Railway...${NC}"
    railway login || railway logout && railway login
    railway up --service-name=localbookr-api || {
        echo -e "${RED}❌ Railway deployment failed${NC}"
        BACKEND_SUCCESS=false
    }
    BACKEND_SUCCESS=true
elif command -v render &> /dev/null; then
    # Deploy to Render
    echo -e "${BLUE}Deploying to Render...${NC}"
    render deploy || {
        echo -e "${RED}❌ Render deployment failed${NC}"
        BACKEND_SUCCESS=false
    }
    BACKEND_SUCCESS=true
else
    echo -e "${YELLOW}⚠️ Backend deployment skipped (no Railway/Render found)${NC}"
    echo -e "${BLUE}💡 Manual backend deployment required${NC}"
    BACKEND_SUCCESS=false
fi

# Step 6: Database Setup
echo -e "${YELLOW}🗄️ Setting up database...${NC}"

if command -v supabase &> /dev/null; then
    # Supabase setup
    echo -e "${BLUE}Connecting to Supabase...${NC}"
    npx supabase db push || {
        echo -e "${RED}❌ Supabase database setup failed${NC}"
        DATABASE_SUCCESS=false
    }
    DATABASE_SUCCESS=true
else
    echo -e "${YELLOW}⚠️ Manual database setup required${NC}"
    DATABASE_SUCCESS=false
fi

# Step 7: Environment Variables Configuration
echo -e "${YELLOW}⚙️ Environment Variables Setup${NC}"

cat > .netlify-env << 'EOF
# LocalBookr Platform Environment Variables
# Generated by deploy script - $(date)

# Frontend Configuration
NEXT_PUBLIC_API_URL=https://api-localbookr.netlify.app
NEXT_PUBLIC_APP_NAME=LocalBookr
NEXT_PUBLIC_ENVIRONMENT=production

# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here

# Database (for backend functions)
DATABASE_URL=postgresql://postgres.your-password@your-host:5432/localbookr

# Authentication
JWT_SECRET=your-super-secret-jwt-key-change-this

# WhatsApp/SMS
TWILIO_ACCOUNT_SID=your-twilio-account-sid
TWILIO_AUTH_TOKEN=your-twilio-auth-token
TWILIO_WHATSAPP_NUMBER=whatsapp:+14155238886

# File Storage
CLOUDINARY_CLOUD_NAME=your-cloudinary-name
CLOUDINARY_API_KEY=your-cloudinary-api-key
CLOUDINARY_API_SECRET=your-cloudinary-secret

# Rate Limiting
API_RATE_LIMIT_ENABLED=true
NOTIFICATION_RATE_LIMIT_ENABLED=true

# Platform Settings
PLATFORM_COMMISSION_RATE=10
MINIMUM_BOOKING_AMOUNT=50
MAXIMUM_BOOKING_ADVANCE_DAYS=90
CANCELLATION_POLICY_HOURS=24
AUTOMATIC_REMINDER_HOURS=2
EOF

echo -e "${GREEN}✅ Environment variables template created${NC}"
echo -e "${BLUE}📋 Edit .netlify-env and add your actual API keys${NC}"

# Step 8: Push to GitHub
echo -e "${YELLOW}📤 Pushing to GitHub repository...${NC}"
git push origin main || {
    echo -e "${RED}❌ GitHub push failed${NC}"
    GITHUB_SUCCESS=false
}
GITHUB_SUCCESS=true

# Step 9: Generate Environment Variables Guide
echo -e "${YELLOW}📖 Generating environment setup guide...${NC}"

cat > SETUP_ENVIRONMENT.md << 'EOF'
# LocalBookr Environment Variables Setup Guide

## 🚀 Quick Setup Instructions

### 1. Netlify Dashboard Setup
1. Go to [app.netlify.com](https://app.netlify.com)
2. Select your deployed site
3. Go to Site settings → Build & deploy → Environment
4. Add all variables from .netlify-env

### 2. Required API Keys & Services

#### **Database (Supabase)**
- Create account at [supabase.com](https://supabase.com)
- Get Project URL and Service Role Key
- Add to NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY

#### **WhatsApp/SMS (Twilio)**
- Create account at [twilio.com](https://twilio.com)
- Get Account SID, Auth Token, WhatsApp Number
- Add to environment variables

#### **File Storage (Cloudinary)**
- Create account at [cloudinary.com](https://cloudinary.com)
- Get Cloud Name, API Key, API Secret
- Add to environment variables

### 3. Environment Variables List

#### Frontend Variables:
- \`NEXT_PUBLIC_API_URL\`: Your deployed API URL
- \`NEXT_PUBLIC_SUPABASE_URL\`: Supabase project URL
- \`NEXT_PUBLIC_SUPABASE_ANON_KEY\`: Supabase anon key

#### Backend Variables:
- \`DATABASE_URL\`: PostgreSQL connection string
- \`JWT_SECRET\`: Secret for JWT tokens
- \`TWILIO_ACCOUNT_SID\`: Twilio account SID
- \`TWILIO_AUTH_TOKEN\`: Twilio auth token
- \`TWILIO_WHATSAPP_NUMBER\`: Twilio WhatsApp number
- \`CLOUDINARY_CLOUD_NAME\`: Cloudinary cloud name
- \`CLOUDINARY_API_KEY\`: Cloudinary API key
- \`CLOUDINARY_API_SECRET\`: Cloudinary API secret

### 4. Testing Setup

After setting up environment variables:

1. Test Admin Panel:
   - Visit: https://localbookr-admin.netlify.app
   - Login: admin@localbookr.com / admin123

2. Test Customer App:
   - Visit: https://localbookr-customer.netlify.app
   - Test search and booking

3. Test Backend API:
   - Health check: https://api-localbookr.netlify.app/api/v1/health
   - Authentication test

## 📞 Support

For deployment support:
- Check logs in Netlify dashboard
- Verify all environment variables are set
- Check Railway/Render dashboard for backend status
- Review build logs for any errors

## 🔧 Manual Deployment Commands

If automatic deployment fails:

### Netlify Manual Deploy:
\`\`\`bash
# Frontend
netlify deploy --prod --dir=frontend/.next --site=localbookr-customer
netlify deploy --prod --dir=admin-dashboard/.next --site=localbookr-admin
netlify deploy --prod --dir=partner-dashboard/.next --site=localbookr-partner

# Backend (Railway)
railway login
railway up --service-name=localbookr-api

# Backend (Render)
render deploy
\`\`\`

### Database Setup:
\`\`\`bash
# Supabase
npx supabase db push
npx supabase seed

# PostgreSQL (if using local)
createdb localbookr
create user localbookr with password 'securepassword';
grant all privileges on localbookr.* to localbookr;
\`\`\`
EOF

echo -e "${GREEN}✅ Setup guide created: SETUP_ENVIRONMENT.md${NC}"

# Step 10: Final Summary
echo -e "${BLUE}📊 Deployment Summary${NC}"
echo "=================================="
echo -e "LocalBookr Platform Deployment Status:"
echo -e "=================================="
echo -e "📋 Git Repository: $GITHUB_REPO"
echo -e "🌐 Frontend Deployments:"
if [ "$FRONTEND_SUCCESS" = true ]; then
    echo -e "  ✅ Customer App: https://localbookr-customer.netlify.app"
    echo -e "  ✅ Admin Dashboard: https://localbookr-admin.netlify.app"
    echo -e "  ✅ Partner Dashboard: https://localbookr-partner.netlify.app"
else
    echo -e "  ❌ Frontend deployments had issues"
fi
echo -e "⚙ Backend Deployment: $([ "$BACKEND_SUCCESS" = true ] && echo "✅ Railway/Render: Deployed" || echo "❌ Railway/Render: Failed")"
echo -e "🗄️ Database: $([ "$DATABASE_SUCCESS" = true ] && echo "✅ Supabase: Ready" || echo "⚠️ Manual setup required")"
echo -e "=================================="
echo -e "📖 Files Generated:"
echo -e "  ✅ .netlify-env (environment variables template)"
echo -e "  ✅ SETUP_ENVIRONMENT.md (setup instructions)"
echo -e "=================================="

if [ "$FRONTEND_SUCCESS" = true ] && [ "$BACKEND_SUCCESS" = true ] && [ "$DATABASE_SUCCESS" = true ]; then
    echo -e "${GREEN}🎉 LocalBookr platform successfully deployed!${NC}"
    echo -e "${BLUE}🌐 Access URLs:${NC}"
    echo -e "  👥 Customer App: https://localbookr-customer.netlify.app"
    echo -e "  👤 Admin Panel: https://localbookr-admin.netlify.app"
    echo -e "  👥 Partner Dashboard: https://localbookr-partner.netlify.app"
    echo -e "  📊 Setup Guide: SETUP_ENVIRONMENT.md"
else
    echo -e "${YELLOW}⚠️ Deployment completed with manual steps required${NC}"
    echo -e "Please follow SETUP_ENVIRONMENT.md for final configuration"
fi

# Make script executable
chmod +x deploy.sh